"""
Google GenAI (Vertex AI) Service.
Uses Google's Gemini models via Vertex AI to generate text.
"""

from google.oauth2.service_account import Credentials
import vertexai
from vertexai.generative_models import GenerativeModel

from sic_framework import SICComponentManager
from sic_framework.core.service_python2 import SICService
from sic_framework.core.connector import SICConnector
from sic_framework.core.message_python2 import (
    SICConfMessage,
    SICRequest,
    SICMessage,
)

class GoogleGenAIConf(SICConfMessage):
    """
    Configuration for Google Vertex AI (Gemini).
    
    :param keyfile_json: Dict of google service account json key file.
    :param project_id: Google Cloud project ID.
    :param location: Google Cloud region
    :param model_name: Name of the model to use (e.g., "gemini-1.5-flash-001").
    """
    def __init__(
        self,
        keyfile_json: dict,
        project_id: str,
        location: str = "europe-west4",
        model_name: str = "gemini-2.5-flash"
    ):
        super(GoogleGenAIConf, self).__init__()
        self.keyfile_json = keyfile_json
        self.project_id = project_id
        self.location = location
        self.model_name = model_name

class GenAIRequest(SICRequest):
    """
    Request to generate text from a prompt.
    """
    def __init__(self, prompt: str):
        super(GenAIRequest, self).__init__()
        self.prompt = prompt

class GenAIResult(SICMessage):
    """
    The text generated by the LLM.
    """
    def __init__(self, text: str):
        self.text = text

class GoogleGenAIService(SICService):
    """
    SIC Service that wraps Google Vertex AI.
    """
    def __init__(self, *args, **kwargs):
        super(GoogleGenAIService, self).__init__(*args, **kwargs)
        
        # Initialize Vertex AI with the provided credentials
        credentials = Credentials.from_service_account_info(self.params.keyfile_json)
        
        vertexai.init(
            project=self.params.project_id,
            location=self.params.location,
            credentials=credentials
        )
        
        self.model = GenerativeModel(self.params.model_name)
        self.chat_session = None # You could maintain chat history here if desired

    @staticmethod
    def get_inputs():
        return [GenAIRequest]

    @staticmethod
    def get_output():
        return GenAIResult

    @staticmethod
    def get_conf():
        return GoogleGenAIConf()

    def on_request(self, request):
        if type(request).__name__ == "GenAIRequest" or isinstance(request, GenAIRequest):
            return self.generate_content(request)
        else:
            raise ValueError(f"Unknown request type: {type(request)}")

    def generate_content(self, request):
        try:
            # Call Gemini
            response = self.model.generate_content(request.prompt)
            return GenAIResult(text=response.text)
        except Exception as e:
            self.logger.error(f"GenAI Error: {e}")
            return GenAIResult(text="I'm having trouble thinking right now.")

class GoogleGenAI(SICConnector):
    component_class = GoogleGenAIService

if __name__ == "__main__":
    SICComponentManager([GoogleGenAIService], name="GoogleGenAI")