GUESS_RESPONSES = "Are you thinking of a {animal}?"
STUCK_REASK_RESPONSE = "I'm having trouble guessing your animal. Let's revisit some already asked questions!"
STUCK_RESET_RESPONSE = "I couldn't guess your animal based on your answers, i'm stuck between these animals: {stuck_animals}. Tell me when you want to reset"
CORRECT_GUESS_RESPONSE = "yipie, I got it correct! Your animal is indeed a {animal}. Tell me when you want to reset."
WRONG_GUESS_RESPONSE = "Oh no, I couldn't guess your animal. Let me think of something else."
START_OVER_RESPONSE = "I am sorry but I don't know your animal. My best guess is a {highest_likelihood_animal} Tell me when you want to reset."
